### ISSUE TITLE
Option to update the same endpoint?

### ISSUE THREAD

**Issue by theraw** [LINKIWI/endpoint#4]
Hello,

I have some scripts in php, those runs daily and stores their data in `.json` so then i use that `.json` around my sites to display that data. And i don't have why to send api requests in live time on backends because it can make my site to run slow!

So i just saw your project and i like it and i want to use it!
But my scripts example will get data from `example.com/user` , and will save that on `user.json` then on my site i can use that `user.json` to show user data. Everyday my `.php` scripts runs automatically and updates `user.json` with new data. So this is what i was thinking to do with your app.

But with your app i see no option to update the same endpoint, 
```there was an error submitting your endpoint.an endpoint with this name already exists. please choose another name.```

Any idea if i can do this with your project?

Thank you.

**Comment by LINKIWI** [comment]
Hi, are you running your sites behind a web server like Apache/nginx? It sounds to me like the best way to solve your problem is to directly alias a route on your web server to the .json file stored on disk, without even needing to through an intermediary service like this one.

If you're using Apache, for example, you can do `Alias /api/user /path/to/user.json` and make requests to `/api/user` in your frontend. user.json seems to be updated on disk automatically so your web server need not concern itself with hoe its contents on disk change.

**Comment by theraw** [comment]
I'm using Nginx, Creating Alias isn't bad. Just i was thinking to use your script because it can be easy for me, i mean i don't have why to open, edit, reload nginx everytime when i add something new, meanwhile i can just put data to your script with a simple request and i can just edit html/php files to show that data. 

However if isn't prossible isn't problem!
